<?php

/**
 * @file
 * Demonstrates use of the Cron API in Drupal - hook_cron().
 */

use \Drupal\user\Entity\User;

/**
 * @defgroup cull_users Example: Cron
 * @ingroup examples
 * @{
 * Example using Cron API, including hook_cron() and @QueueWorker plugins
 *
 * This example is part of the Examples for Developers Project
 * which you can download and experiment with at
 * http://drupal.org/project/examples
 */

/**
 * Implements hook_cron().
 *
 * We implement hook_cron() to do "background" processing. It gets called every
 * time the Drupal cron runs. We then decide what has to happen in response.
 *
 * In this example, we log a message after the time given in the state value
 * 'cull_users.next_execution'. Then we update that variable to a time in the
 * future.
 */
function cull_users_cron() {
  // We access our configuration.
  $cron_config = \Drupal::configFactory()->getEditable('cull_users.settings');
  // Default to an hourly interval. Of course, cron has to be running at least
  // hourly for this to work.
  $interval = $cron_config->get('interval');
  $interval = !empty($interval) ? $interval : 3600;

  // We usually don't want to act every time cron runs (which could be every
  // minute) so keep a time for the next run in the site state.
  $next_execution = \Drupal::state()->get('cull_users.next_execution');
  $next_execution = !empty($next_execution) ? $next_execution : 0;
  if (REQUEST_TIME >= $next_execution) {
    // Find all users
    $ids = \Drupal::entityQuery('user')
    ->condition('status', 1)
    ->execute();
    $users = User::loadMultiple($ids);

    $authenticated_only = array('authenticated');

    $users_to_delete = array();
    foreach ($users as $key => $user) {
      $roles = $user->getRoles();
      if ($roles == $authenticated_only) {
        $users_to_delete[] = $key;
      }
    }
    if (!empty($users_to_delete)) {
      $cull_count = count($users_to_delete);
      user_delete_multiple($users_to_delete);
      \Drupal::logger('cull_users')->notice('cull_users deleted @count users.', [ '@count' => $cull_count, ]);
    }
    else {
      \Drupal::logger('cull_users')->notice('cull_users found no users to delete.');
    }

    if (\Drupal::state()->get('cull_users_show_status_message')) {
      drupal_set_message(t('cull_users executed at %time', ['%time' => date_iso8601(REQUEST_TIME)]));
    }

    \Drupal::state()->set('cull_users.next_execution', REQUEST_TIME + $interval);
  }

 }

/**
 * output expanded array/structure temporary
 * @param  object or array $any stuff to dump out
 * @param  string optional label
 * @return null
 */
function cull_users_dumpt($any, $what = '') {
  if (\Drupal::state()->get('cull_users_show_status_message')) {
    $dump = print_r($any, TRUE);
    drupal_set_message(t('%label: <pre>%dump</pre>', ['%label' => $what, '%dump' => $dump]));
    //\Drupal::state()->set('cull_users_show_status_message', FALSE);
  }
}
/**
 * @} End of "defgroup cull_users".
 */
