<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cull_users_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.cull_users':
      return t('
        <h2>Cull Users.</h2>
        <h3>Instructions</h3>
        <p>Unpack in the <em>modules</em> folder (currently in the root of your Drupal 8 installation) and enable in <strong>/admin/modules</strong>.</p>
        ');
      break;
  }
}
