<?php

/**
 * @file
 * Demonstrates use of the Cron API in Drupal - hook_cron().
 */

use \Drupal\user\Entity\User;

/**
 * @defgroup cull_users Example: Cron
 * @ingroup examples
 * @{
 * Example using Cron API, including hook_cron() and @QueueWorker plugins
 *
 * This example is part of the Examples for Developers Project
 * which you can download and experiment with at
 * http://drupal.org/project/examples
 */

/**
 * Implements hook_cron().
 *
 * We implement hook_cron() to do "background" processing. It gets called every
 * time the Drupal cron runs. We then decide what has to happen in response.
 *
 * In this example, we log a message after the time given in the state value
 * 'cull_users.next_execution'. Then we update that variable to a time in the
 * future.
 */
function cull_users_cron() {
  // We access our configuration.
  $cron_config = \Drupal::configFactory()->getEditable('cull_users.settings');
  // Default to an hourly interval. Of course, cron has to be running at least
  // hourly for this to work.
  $interval = $cron_config->get('interval');
  $interval = !empty($interval) ? $interval : 3600;

  // We usually don't want to act every time cron runs (which could be every
  // minute) so keep a time for the next run in the site state.
  $next_execution = \Drupal::state()->get('cull_users.next_execution');
  $next_execution = !empty($next_execution) ? $next_execution : 0;
  if (REQUEST_TIME >= $next_execution) {
    // This is a silly example of a cron job.
    // It just makes it obvious that the job has run without
    // making any changes to your database.
    \Drupal::logger('cull_users')->notice('cull_users ran');
    if (\Drupal::state()->get('cull_users_show_status_message')) {
      drupal_set_message(t('cull_users executed at %time', ['%time' => date_iso8601(REQUEST_TIME)]));
      \Drupal::state()->set('cull_users_show_status_message', FALSE);
    }
    \Drupal::state()->set('cull_users.next_execution', REQUEST_TIME + $interval);
  }
}

/**
 * @} End of "defgroup cull_users".
 */
