cull_users.settings:
  type: config_object
  label: 'Cull Users settings'
  mapping:
    cull_users:
      type: mapping
      mapping:
        page_title:
          type: text
          label: 'Cull Users generator page title:'
        source_text:
          type: text
          label: 'Source text for Cull Users generation:'
block.settings.cull_users_block:
  type: block_settings
  label: 'Cull Users block'
  mapping:
    cull_users_block_settings:
